### ISSUE TITLE
how to deploy on cloudfare

### ISSUE THREAD

**Issue by Badaryman** [Danushka-Madushan/Animepahe#2]
i cant seem to deploy it on cloudfare even though i already deployed the api
and where to change api

**Comment by Badaryman** [comment]
![image](https://github.com/Danushka-Madushan/Animepahe/assets/154390732/bc1816a8-0aa0-432c-9776-f8a10583d94d)

**Comment by Badaryman** [comment]
![image](https://github.com/Danushka-Madushan/Animepahe/assets/154390732/2867df82-b9eb-4caa-b4ef-b22288625a5b)

**Comment by Badaryman** [comment]
<html>
<body>
<pre class="c_oj c_bv c_os c_sy c_yf c_yg c_db c_zp c_zq c_zr c_zs c_ey c_ez c_ze c_bx c_zt" style="box-sizing: border-box; border-radius: 0px; color: rgb(49, 49, 49); display: block; font-size: 12px; margin: 0px; overflow: auto; padding: 16px 32px; width: 894.4px; background-color: rgb(242, 242, 242); border-width: 0px 0px 1px; border-style: solid; border-color: rgb(217, 217, 217); border-image: initial; font-family: monaco, courier, monospace; height: 500px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
01:22:54.365 | [info] [nitro] Initializing prerenderer
-- | --
01:22:55.574 | [info] [nitro] Prerendering 2 routes
01:22:55.651 | [log] [nitro]   ├─ /_ipx/h_205&f_png&blur_10&q_50/pahe.png (74ms)
01:22:55.652 | │ └── Error: [404] Page not found: /_ipx/h_205&f_png&blur_10&q_50/pahe.png
01:22:55.652 | [log] [nitro]   ├─ /_ipx/h_384&f_png&blur_10&q_50/pahe.png (73ms)
01:22:55.652 | │ └── Error: [404] Page not found: /_ipx/h_384&f_png&blur_10&q_50/pahe.png
01:22:55.653 | [log] [nitro]
01:22:55.653 | Errors prerendering:
01:22:55.653 | [log] [nitro]   ├─ /_ipx/h_205&f_png&blur_10&q_50/pahe.png (74ms)
01:22:55.653 | │ └── Error: [404] Page not found: /_ipx/h_205&f_png&blur_10&q_50/pahe.png
01:22:55.654 | [log] [nitro]   ├─ /_ipx/h_384&f_png&blur_10&q_50/pahe.png (73ms)
01:22:55.654 | │ └── Error: [404] Page not found: /_ipx/h_384&f_png&blur_10&q_50/pahe.png
01:22:55.654 | [log] [nitro]
01:22:55.654 | [error] Exiting due to prerender errors.
01:22:55.654 | at prerender (node_modules/nitropack/dist/shared/nitro.3d0a4b01.mjs:214:11)
01:22:55.654 | at async node_modules/nuxt/dist/index.mjs:2986:7
01:22:55.654 | at async build (node_modules/nuxt/dist/index.mjs:4375:5)
01:22:55.655 | at async Object.run (node_modules/nuxi/dist/chunks/build.mjs:92:5)
01:22:55.655 | at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.c6444792.mjs:1647:7)
01:22:55.655 | at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.c6444792.mjs:1638:11)
01:22:55.655 | at async runMain$1 (node_modules/nuxi/dist/shared/nuxi.c6444792.mjs:1770:7)
01:22:55.655 |  
01:22:55.655 | [error] Exiting due to prerender errors.
01:22:55.694 | Failed: Error while executing user command. Exited with error code: 1
01:22:55.704 | Failed: build command exited with code: 1
01:22:56.716 | Failed: error occurred while running build command

</pre><div class="c_fz c_ga c_d" style="box-sizing: border-box; display: flex; padding-top: 32px; padding-bottom: 32px; color: rgb(49, 49, 49); font-family: -apple-system, system-ui, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Helvetica Neue&quot;, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><button type="button" class="c_ir c_is c_ip c_iq c_it c_iu c_iv c_iw c_ix c_iy c_iz c_ja c_jb c_ab c_s c_t c_jc c_ee c_dy c_ho c_jd c_je c_jf c_jg c_jh c_ji c_jj c_n c_u c_jk c_jl c_jm c_av c_jn c_jo c_al c_gz c_du c_ea c_dl c_bq c_bm c_jp c_jq c_jr c_js c_do c_jt c_ju" style="box-sizing: border-box; font-size: 14px; font-family: -apple-system, system-ui, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Helvetica Neue&quot;, Arial, sans-serif; border: none; position: relative; align-items: center; -webkit-box-align: center; justify-content: center; -webkit-box-pack: center; text-align: center; cursor: pointer; white-space: normal; user-select: none; padding: 8px 16px; margin: 0px 0px 0px auto; line-height: 1.2; font-weight: 400; border-radius: 4px; opacity: inherit; pointer-events: auto; transition-property: all; transition-duration: 300ms; transition-timing-function: ease; max-width: initial; float: none; background-color: rgb(5, 109, 255); color: rgb(255, 255, 255); display: inline-flex; width: auto;"><span style="box-sizing: border-box;">Retry deployment</span></button></div><br class="Apple-interchange-newline">
</body>
</html>

**Comment by Badaryman** [comment]
[anime.10339e4c-35af-4fd3-be24-31dbd7b4d9d8.log](https://github.com/Danushka-Madushan/Animepahe/files/13821823/anime.10339e4c-35af-4fd3-be24-31dbd7b4d9d8.log)

**Comment by Badaryman** [comment]
![image](https://github.com/Danushka-Madushan/Animepahe/assets/154390732/47a2e3ec-2b80-4ab4-baf5-762e4801fe92)
![image](https://github.com/Danushka-Madushan/Animepahe/assets/154390732/0bb545bd-6deb-4c0b-b9fe-e6ac33cb7dda)

**Comment by Danushka-Madushan** [comment]
@Badaryman Cloudflare Pages is not yet fully supported to nuxt.js. you may build the frontend first and then you can upload it into pages as a static site.

**Comment by Badaryman** [comment]
Please Check @Danushka-Madushan 
https://animepahee.pages.dev/

with extra e
