### ISSUE TITLE
there is ddos guard in animepahe website

### ISSUE THREAD

**Issue by Badaryman** [Danushka-Madushan/Animepahe#3]
Please Update

**Comment by Danushka-Madushan** [comment]
Thank you for bringing this to our attention. We are aware of the DDoS guard on the Animepahe website. We are currently in the process of designing a system to bypass this. We appreciate your patience and understanding during this time. We will update the system as soon as the new design is ready. Until then, we kindly ask for your patience. Thank you.

**Comment by Badaryman** [comment]
ty

**Comment by Badaryman** [comment]
@Danushka-Madushan any update?

**Comment by Danushka-Madushan** [comment]
@Badaryman :/

**Comment by Danushka-Madushan** [comment]
@Badaryman DDoS Guard has been bypassed Successfully

**Comment by Badaryman** [comment]
> @Badaryman DDoS Guard has been bypassed Successfully

ty @Danushka-Madushan working now and websites loads faster nos
